Fix to stop Box2D being wrapped with ST_AsEWKB
geoalchemy/geoalchemy2 pull request #375
Opened 2022-03-18 07:40 UTC by EdwardBetts

Version 0.9.0 broke my code. My query was returning a string from Box2D(), since version 0.9.0 the call to Box2D() gets wrapped by ST_AsEWKB. This change fixes my problem so I can get a string back from Box2D().

2022-03-18 07:41 UTC, EdwardBetts commented
``` python
from geoalchemy2 import Geometry
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy import func

session = scoped_session(sessionmaker())

stmt = session.query(func.ST_Dump(Geometry()).label("x")).subquery()

print(session.query(func.Box2D(stmt.c.x.geom)))
```

2022-03-18 18:03 UTC, adrien-berchet commented
Hi @EdwardBetts 
Thanks for this, it's indeed probably better for now. Maybe I will add a Box type later but for now let's not wrap it.
Could you just also remove the wrapping for Box3D please?

2022-03-18 18:04 UTC, adrien-berchet requested changes

2022-03-18 18:04 UTC, adrien-berchet commented on geoalchemy2/_functions.py
>      ('Box3D', types.Geometry,
```suggestion
    ('Box3D', None,
```

2022-03-18 18:04 UTC, EdwardBetts commented
Will do

2022-03-19 08:46 UTC, adrien-berchet commented
Thanks @EdwardBetts , I updated a few other functions for consistency, does it looks good to you?

2022-03-19 10:17 UTC, adrien-berchet approved these changes

2022-03-19 10:27 UTC, EdwardBetts commented
Looks good to me.

2022-03-19 10:33 UTC, merged

2022-03-19 10:33 UTC, adrien-berchet commented
Thanks!